version: '3'

services:
  platform:
    build:
      context: .
      dockerfile: ./apps/platform/Dockerfile
    ports:
     - "4200:80"
    command: "npm run start:platform"
        
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
     - "3000:3000"
    command: "npm run start:server"

